name: Build and test

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Test and build
        run: make prep-deploy
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifacts
          path: build-artifacts/
          retention-days: 2
