name: Build and test

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Authenticate to packages
        run: dotnet nuget add source --username Virtual-Finland-Development --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Virtual-Finland-Development/index.json"
      - name: Test and build
        run: make prep-deploy
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI/bin/Release/net6.0/VirtualFinland.UsersAPI.zip
          retention-days: 2
      - name: Upload database migrator artifact
        uses: actions/upload-artifact@v3
        with:
          name: DatabaseMigrator_Artifacts
          path: VirtualFinland.UsersAPI.DatabaseMigrationRunner/bin/Release/net6.0/VirtualFinland.UsersAPI.DatabaseMigrationRunner.zip
          retention-days: 2
