name: Manually deploy to selected environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: true

env:
  PULUMI_STACK: dev
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN}}

jobs:
  build-and-test:
    name: Build and test
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Pulumi Users API Integration Tests
        run: dotnet test ./VirtualFinland.UsersAPI.UnitTests --no-restore
      - name: Install AWS Dotnet CLI Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Build UserAPI Lamda Package
        working-directory: ./VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI
        run: dotnet lambda package
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: /home/runner/work/users-api/users-api/VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI/bin/Release/net6.0/VirtualFinland.UsersAPI.zip
          retention-days: 2
  deploy:
    name: Deploy to AWS ${{ inputs.environment }} environment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./
      - name: Select Pulumi Stack
        working-directory: ./VirtualFinland.UsersAPI.Deployment
        run: pulumi stack select ${{ secrets.PULUMI_ORGANIZATION }}/${{ inputs.environment }}
      - name: Set Pulumi Artifact Path
        working-directory: ./VirtualFinland.UsersAPI.Deployment
        run: pulumi config set appArtifactPath ../VirtualFinland.UsersAPI.zip
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ inputs.environment }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Pulumi Up
        working-directory: ./VirtualFinland.UsersAPI.Deployment
        run: pulumi up -y
      - name: Tag the deployment
        uses: Virtual-Finland-Development/automatic-release-action@v1.0
        if: ${{ inputs.environment == 'staging' }}
        with:
          environment: ${{ inputs.environment }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
