name: "Deploy automatically to development-environment"
on:
  push:
    branches: ["main"]

jobs:
  build-test-and-deploy:
    name: Build, test and deploy
    uses: ./.github/workflows/deploy-to-environment.yml
    secrets: inherit
    with:
      environment: dev
