name: Deploy to the selected environment

on:
  workflow_call:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: true
jobs:
  build-and-test:
    name: Build and test
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Pulumi Users API Integration Tests
        run: dotnet test ./VirtualFinland.UsersAPI.UnitTests --no-restore
      - name: Install AWS Dotnet CLI Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Build UserAPI Lamda Package
        working-directory: ./VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI
        run: dotnet lambda package
      - name: Build DatabaseMigrationRunner Lamda Package
        working-directory: ./VirtualFinland.UsersAPI.DatabaseMigrationRunner
        run: dotnet lambda package
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: /home/runner/work/users-api/users-api/VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI/bin/Release/net6.0/VirtualFinland.UsersAPI.zip
          retention-days: 2
      - name: Upload database migrator artifact
        uses: actions/upload-artifact@v3
        with:
          name: DatabaseMigrator_Artifacts
          path: /home/runner/work/users-api/users-api/VirtualFinland.UsersAPI.DatabaseMigrationRunner/bin/Release/net6.0/VirtualFinland.UsersAPI.DatabaseMigrationRunner.zip
          retention-days: 2
  deploy:
    name: "Deploy to AWS ${{ inputs.environment }}-environment"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      DEPLOYMENT_EVENT_IDENT: users-api-deployment-${{ inputs.environment }}-${{ github.sha }}-${{ github.run_number }}
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./
      - uses: actions/download-artifact@v3
        with:
          name: DatabaseMigrator_Artifacts
          path: ./
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ inputs.environment }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Resolve Database identifier with Pulumi
        id: get-pulumi-outputs
        continue-on-error: true # Continue if db does not yet exist
        working-directory: ./VirtualFinland.UsersAPI.Deployment
        run: |
          pulumi stack select ${{ secrets.PULUMI_ORGANIZATION }}/${{ inputs.environment }}
          echo "DBIdentifier=$(pulumi stack output DBIdentifier)" >> $GITHUB_OUTPUT
          echo "DatabaseMigratorLambdaArn=$(pulumi stack output DatabaseMigratorLambdaArn)" >> $GITHUB_OUTPUT
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Create database backup snapshot on PRE-deployment
        continue-on-error: true # TODO: needs a check if db exists but snapshot creation fails
        run: |
          aws rds create-db-snapshot --db-instance-identifier ${{ steps.get-pulumi-outputs.outputs.DBIdentifier }} --db-snapshot-identifier PRE-${{ env.DEPLOYMENT_EVENT_IDENT }}
      - name: Deploy with Pulumi
        id: pulumi-up
        uses: pulumi/actions@v4
        with:
          work-dir: ./VirtualFinland.UsersAPI.Deployment
          command: up
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/${{ inputs.environment }}
          upsert: true
          config-map: "{ appArtifactPath: { value: ../VirtualFinland.UsersAPI.zip, secret: false }, dbMigratorArtifactPath: { value: ../VirtualFinland.UsersAPI.DatabaseMigrationRunner.zip, secret: false } }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Invoke database migration runner lambda
        run: |
          aws lambda invoke --function-name ${{ steps.get-pulumi-outputs.outputs.DatabaseMigratorLambdaArn }} output.json
          cat output.json
      - name: Tag the deployment
        uses: Virtual-Finland-Development/automatic-release-action@v1.0
        if: ${{ inputs.environment == 'staging' }}
        with:
          environment: ${{ inputs.environment }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
