name: "Deploy automatically to development-environment"
on:
  push:
    branches: ["main"]

jobs:
  build-test-and-deploy:
    uses: Virtual-Finland-Development/users-api/.github/workflows/deploy-to-environment.yml@main
    secrets: inherit
    with:
      environment: dev
