name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore NuGet Packages
        run: dotnet restore ./VirtualFinland.UsersAPI.sln
      - name: Build Solution
        run: dotnet build ./VirtualFinland.UsersAPI.sln --no-restore --verbosity normal
      - name: Pulumi Users API Integration Tests
        run: dotnet test ./VirtualFinland.UsersAPI.UnitTests --no-restore --verbosity normal
      - name: Install AWS Dotnet CLI Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Build UserAPI Lamda Package
        working-directory: ./VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI
        run: dotnet lambda package
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: /home/runner/work/users-api/users-api/VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI/bin/Release/net6.0/VirtualFinland.UsersAPI.zip
          retention-days: 2
  preview-pulumi:
    name: Preview Pulumi
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    env:
      TEST_ENVIRONMENT: dev
    steps:
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ env.TEST_ENVIRONMENT }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          work-dir: ./VirtualFinland.UsersAPI.Deployment
          command: preview
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/${{ env.TEST_ENVIRONMENT }}
          config-map: "{ appArtifactPath: { value: ../VirtualFinland.UsersAPI.zip, secret: false } }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
