name: Run Tests

on:
  pull_request:
    branches:
      - main

env:
  TEST_ENVIRONMENT: dev
jobs:
  build-and-test:
    name: Build and test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  preview-pulumi:
    name: Preview Pulumi
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Application_Artifacts
          path: ./VirtualFinland.UserAPI/src/VirtualFinland.UsersAPI/bin/Release/net6.0/
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ env.TEST_ENVIRONMENT }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          work-dir: ./VirtualFinland.UsersAPI.Deployment
          command: preview
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/${{ env.TEST_ENVIRONMENT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
